name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-image-name:latest
        
    - name: SSH and deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /home/guillianv/dev/sveltekit/sveltekit-begins
          docker-compose down
          git pull
          docker-compose up -d